['female_left_ear_to_female_centre',
       'female_left_ear_to_female_nose',
       'female_left_ear_to_female_right_ear',
       'female_left_ear_to_female_tail', 'female_left_ear_to_male_centre',
       'female_nose_to_female_centre', 'female_nose_to_female_tail',
       'female_nose_to_male_centre', 'female_right_ear_to_female_centre',
       'female_right_ear_to_female_nose',
       'female_right_ear_to_female_tail',
       'female_right_ear_to_male_centre', 'female_tail_to_female_centre',
       'female_tail_to_male_centre', 'male_centre_to_female_centre',
       'male_left_ear_to_female_centre',
       'male_left_ear_to_female_left_ear', 'male_left_ear_to_female_nose',
       'male_left_ear_to_female_right_ear',
       'male_left_ear_to_female_tail', 'male_left_ear_to_male_centre',
       'male_left_ear_to_male_nose', 'male_left_ear_to_male_right_ear',
       'male_left_ear_to_male_tail', 'male_nose_to_female_centre',
       'male_nose_to_female_left_ear', 'male_nose_to_female_nose',
       'male_nose_to_female_right_ear', 'male_nose_to_female_tail',
       'male_nose_to_male_centre', 'male_nose_to_male_tail',
       'male_right_ear_to_female_centre',
       'male_right_ear_to_female_left_ear',
       'male_right_ear_to_female_nose',
       'male_right_ear_to_female_right_ear',
       'male_right_ear_to_female_tail', 'male_right_ear_to_male_centre',
       'male_right_ear_to_male_nose', 'male_right_ear_to_male_tail',
       'male_tail_to_female_centre', 'male_tail_to_female_left_ear',
       'male_tail_to_female_nose', 'male_tail_to_female_right_ear',
       'male_tail_to_female_tail', 'male_tail_to_male_centre']